@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbGxvMSIsImlhdCI6MTc3OTM4NDUyOCwiZXhwIjoxNzc5Mzg1MTI4fQ.K9V7JlrVfASID7PRujoY4bSsjA1YFEu49bKWqObLc9sCmDeK6MHgbYKNqK8z0kvSSSYWyETxfjYOlTXRE1zRK2MACw6CKdUTfwlkUOpzxswMS1pK6T-Vbcb3crOgUMflxf7Py7D5pkvvQMvX1M5z6IfSch0Q3R4o8KiEeImTgA9rCtxRehN4KFx90Uj7miHMyA88QeQjojEHOeQ8sG9yeIXzDB9LHgsF1dZ8S5rbfdmaSdJeoRiolWcCG7PmdLYvYo9nsiYXnP4YpyfHyi354uqe0VeFeM8ZaUYRmadk0K9UucL3yjNwpCPY6da_abNz_SlaHcm642PNjNBGik1K8g

GET http://localhost:4000/me HTTP/1.1
Authorization: Bearer {{token}}

###

POST http://localhost:3000/signup
Content-Type: application/json

{
  "username": "Hello1",
  "password": "Hi"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Hello1",
  "password": "Hi"
}